version: "3"
services:
  jenkins:
    image: registry.cn-shenzhen.aliyuncs.com/a852203465/jenkins:1.4-jdk8
    container_name: jenkins
    restart: always
    ports:
      - "9100:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS="-Xms512m -Xmx1024m"
      - TZ=Asia/Shanghai
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/jenkins/home:/var/jenkins_home
      - ./conf/daemon.json:/etc/docker/daemon.json
      - ./conf/settings.xml:/opt/apache-maven-3.8.4/conf/settings.xml
      - ./conf/defaults.js:/opt/node-v19.7.0-linux-x64/lib/node_modules/npm/lib/config/defaults.js
      - ./conf/init.gradle:/opt/gradle-8.0.1/init.d/init.gradle
    networks:
      - jenkins_net


networks:
  jenkins_net:
    external: true

















